apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-on-k8s-deployment
  labels:
    app: springboot-on-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-on-k8s
  template:
    metadata:
      labels:
        app: springboot-on-k8s
    spec:
      containers:
      - name: springboot-on-k8s
        image: benisrael/springboot-on-k8s:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s-service
spec:
  type: NodePort
  selector:
    app: springboot-on-k8s
  ports:
    - protocol: 'TCP'
      port: 8080  
      targetPort: 8080